remote_theme: pages-themes/dinky@v0.2.0
lsi: false
safe: true
source: /
highlighter: rouge

incremental: false
gist:
  noscript: false
kramdown:
  parse_block_html: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
